---
version: '3.8'

services:
  herpstat_exporter:
    image: ghcr.io/jjack/herpstat_spyderweb_exporter:latest
    container_name: herpstat_exporter
    command:
      - '--herpstat.address=1.2.3.4'
    ports:
      - 10010:10010
    restart: unless-stopped
