{
 "title": "Herpstat Info",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "system",
    "query": {
     "query": "label_values(herpstat_system_info,name)"
    }
   },
   {
    "name": "output",
    "query": {
     "query": "query_result(herpstat_output_info{system=~\"$system\"})"
    }
   },
   {
    "name": "output_power_limit",
    "query": {
     "query": "query_result(herpstat_output_power_limit{system=~\"$system\",id=~\"$output\"})"
    }
   }
  ]
 },
 "panels": [
  { "title": "$system", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "system" },
  {
   "title": "$system Info",
   "type": "table",
   "gridPos": { "h": 4, "w": 15, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "max(herpstat_system_info{name=~\"$system\"}) by (name, outputs, firmware, ip, mac)"
    }
   ]
  },
  {
   "title": "Internal Temp",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "herpstat_system_temp{name=~\"$system\"}",
     "legendFormat": "Temperature"
    }
   ]
  },
  {
   "title": "System Resets",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "herpstat_system_reset_total{name=~\"$system\"}"
    }
   ]
  },
  {
   "title": "$output Info",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 5 },
   "repeat": "output",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(herpstat_output_info{system=~\"$system\", id=~\"$output\"}) by (id, name, mode)"
    }
   ]
  },
  {
   "title": "$output Error",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 7, "y": 5 },
   "repeat": "output",
   "targets": [
    {
     "expr": "max(herpstat_output_error{system=~\"$system\",id=~\"$output\"}) by (error)",
     "legendFormat": "{{error}}"
    }
   ]
  },
  {
   "title": "$output Power Output",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 11, "y": 5 },
   "repeat": "output",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "herpstat_output_power{system=~\"$system\",id=~\"$output\"}",
     "legendFormat": "Output"
    },
    {
     "expr": "herpstat_output_power_limit{system=~\"$system\",id=~\"$output\"}",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "$output Probe Temp",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 15, "y": 5 },
   "repeat": "output",
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "expr": "herpstat_output_probe_temperature{system=~\"$system\",id=~\"$output\"}",
     "legendFormat": "Temperature"
    },
    {
     "expr": "herpstat_output_alarm_low{system=~\"$system\", id=~\"$output\"}",
     "legendFormat": "Low Alarmx"
    },
    {
     "expr": "herpstat_output_alarm_high{system=~\"$system\",id=~\"$output\"}",
     "legendFormat": "High Alarmx"
    },
    {
     "expr": "herpstat_output_alarm_enabled{system=~\"$system\",id=~\"$output\"}",
     "legendFormat": "Alarm Enabled"
    }
   ]
  },
  {
   "title": "$output Probe Humidity",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 19, "y": 5 },
   "repeat": "output",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "herpstat_output_probe_humidity{id=~\"$output\", system=~\"$system\"}",
     "legendFormat": "Humidity"
    },
    {
     "expr": "herpstat_output_alarm_high{system=~\"$system\",id=~\"$output\"}",
     "legendFormat": "high alarm"
    },
    {
     "expr": "herpstat_output_alarm_low{system=~\"$system\",id=~\"$output\"}",
     "legendFormat": "low alarm"
    },
    {
     "expr": "herpstat_output_alarm_enabled{system=~\"$system\",id=~\"$output\"}",
     "legendFormat": "alarm enabled"
    }
   ]
  }
 ]
}